version: '3.9'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/core:/app
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - SECRET_KEY=replace-this-in-prod
      - DATABASE_URL=sqlite:///db.sqlite3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
      args:
        REACT_APP_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
