name: Deploy via SSH with Docker Compose

on:
  push:
    branches:
      - 27-ci-cd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
        shell: bash

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -p "${{ secrets.DEPLOY_PORT }}" "${{ secrets.DEPLOY_HOST }}" >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy to server via SSH
        run: |
          ssh -i ~/.ssh/deploy_key -p "${{ secrets.DEPLOY_PORT }}" "${{ secrets.DEPLOY_USER }}"@"${{ secrets.DEPLOY_HOST }}" << 'EOF'
            set -e
            cd ~/Database-Playground
            git pull origin main
            docker compose build
            docker compose up -d
          EOF
        shell: bash
